version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/theme-bot
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: npm test-cov
          command: npm run test-cov
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    steps:
      - run:
         name: deploy Bot
         command: 'echo bot deploy!'



workflows:
  version: 2

  deploy:
    jobs:
      - hold:
          type: approval
      - deploy
         requires:
           - hold
          filters: *filter-only-master
