version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.2
    working_directory: ~/themis-bot
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/themis-bot

  install_dependencies:
    working_directory: ~/themis-bot
    docker:
      - image: circleci/node:8.2
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install
      - save_cache:
          key: v1-node-modules-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/themis-bot/node_modules

  build_and_test:
      working_directory: ~/themis-bot
      docker:
        - image: circleci/node:8.2
      steps:
        - restore_cache:
            keys:
              - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - restore_cache:
            keys:
              - v1-node-modules-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: test
            command: npm run test-cov
        - save_cache:
            key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/themis-bot


  deploy:
    machine:
      enabled: true
    working_directory: ~/themis-bot
    steps:
      - restore_cache:
          keys:
            - v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: prune npm node_modules
          command: npm prune --production
      - store_artifacts:
          path: .
      - run:
          name: deploy
          command: 'echo push to prod!'


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - build_and_test:
          requires:
            - install_dependencies
      - hold:
          type: approval
          requires:
            - build_and_test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
