version: 2
jobs:
  build_and_test:
    docker:
    working_directory: ~/theme-bot
      # specify the version you desire here
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
        name: npm test-cov
        command: npm run test-cov
      - store_artifacts:
        path: coverage
        prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
