version: 2
jobs:
  build:
    working_directory: ~/themis-bot
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: ~/themis-bot
          paths:
            - node_modules
  test:
    working_directory: ~/themis-bot
    docker:
      - image: circleci/node:8.9.3
    steps:
      - attach_workspace:
          at: ~/themis-bot
      - run:
          name: Test
          command: ls
      - run:
          name: node_modules
          command: ls node_modules
      - run:
          name: Generate code coverage
          command: npm run test-cov
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
