# version: 2.0
#
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.9.3
#     working_directory: ~/theme-bot
#     steps:
#       - checkout
#       - run:
#           name: update-npm
#           command: 'sudo npm install -g npm@latest'
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#       - run:
#           name: npm install
#           command: npm install
#       - save_cache:
#           key: v1-dependencies-{{ checksum "package.json" }}
#           paths:
#             - node_modules
#       - run:
#           name: npm test-cov
#           command: npm run test-cov
#       - store_artifacts:
#           path: coverage
#           prefix: coverage
#   deploy:
#     machine:
#       enabled: true
#     steps:
#       - run:
#          name: deploy Bot
#          command: 'echo bot deploy!'
#
#
#
# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - hold:
#           type: approval
#       - deploy
#           requires:
#            - hold
#           filters: *filter-only-master

version: 2
jobs:
  build:
    working_directory: ~/themis-bot
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: npm run test-cov
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
