name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'build_and_test'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: yarn install
      - run: yarn test
        env:
          CI: true
      - run: yarn run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
